<?php

return [
    [
        'id' => '4g-lite',
        'name' => '4G Lite',
        'tier' => 'Fast',
        'speed' => 'Fast',
        'monthly' => 69,
        'activation' => 0,
        'activation_orig' => 299,
        'discount' => 'Waived',
        'max_speed' => '60 Mbps',
        'latency' => '40-80 ms',
        'best_for' => 'Browsing, email & casual streaming',
        'audience' => '1-2 people, light use',
        'features' => [
            'Up to 60 Mbps speeds',
            'Unlimited data, zero caps',
            '4G LTE dual-band router included',
            'No contracts -- cancel anytime',
            'Price Lock Guarantee',
        ],
        'color' => '#a1a1aa',
        'speed_dots' => 1,
        'popular' => false,
    ],
    [
        'id' => '4g-plus',
        'name' => '4G Plus',
        'tier' => 'Faster',
        'speed' => 'Faster',
        'monthly' => 99,
        'activation' => 99,
        'activation_orig' => 299,
        'discount' => '67% off',
        'max_speed' => '250 Mbps',
        'latency' => '30-60 ms',
        'best_for' => 'Streaming, video calls & gaming',
        'audience' => 'Households, multi-device',
        'features' => [
            'Up to 250 Mbps speeds',
            'Unlimited data, zero caps',
            '4.5G Cat12 dual-band router included',
            'No contracts -- cancel anytime',
            'Price Lock Guarantee',
        ],
        'color' => '#55b685',
        'speed_dots' => 2,
        'popular' => false,
    ],
    [
        'id' => '5g-ultra',
        'name' => '5G Ultra',
        'tier' => 'Fastest',
        'speed' => 'Fastest',
        'monthly' => 109,
        'activation' => 199,
        'activation_orig' => 299,
        'discount' => '33% off',
        'max_speed' => '500 Mbps',
        'latency' => '20-40 ms',
        'best_for' => '4K streaming, gaming & remote work',
        'audience' => 'Large families, power users',
        'features' => [
            'Up to 500 Mbps speeds',
            'Unlimited data, zero caps',
            'Premium 5G router included',
            'No contracts -- cancel anytime',
            'Price Lock Guarantee',
        ],
        'color' => '#a78bfa',
        'speed_dots' => 3,
        'popular' => true,
    ],
];
